---

- name: Install Roundcube APT packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - '{{ roundcube_base_packages }}'
  when: ansible_pkg_mgr == 'apt'

- name: Generate roundcube apache configuration
  template:
    src: 'apache/apache2-roundcube.sample.conf.j2'
    dest: '/etc/apache2/sites-available/webmail-{{mail_hostname}}.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Enable Apache modules
  apache2_module:
    state: present
    name: '{{item}}'
  with_flattened: 
    - '{{roundcube_apache_modules}}'

- name: Unpack Roundcube
  unarchive:
    src: https://github.com/roundcube/roundcubemail/releases/download/1.3.6/roundcubemail-1.3.6-complete.tar.gz
    dest: /var/www/roundcube
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: Create roundcube database
  mysql_db:
    name: '{{roundcube_mysql_database_name}}'
    state: present

- name: Create database user
  mysql_user:
    name: '{{roundcube_mysql_user_name}}'
    password: '{{roundcube_mysql_password}}'
    priv: '{{roundcube_mysql_database_name}}.*:ALL'
    state: present

- name: Generate roundcube application configuration
  template:
    src: 'roundcube/config.inc.php.j2'
    dest: '/var/www/roundcube/config/config.inc.php'
    owner: 'root'
    group: 'root'
    mode: '0644'


    
- name: Enable roundcube site
  command: a2ensite webmail-{{mail_hostname}}.conf

